export const redVarietals = [
  "Cabernet Sauvignon",
  "Merlot",
  "Pinot Noir",
  "Syrah/Shiraz",
  "Zinfandel",
  "Malbec",
  "Sangiovese",
  "Tempranillo",
  "Grenache/Garnacha",
  "Nebbiolo",
  "Gamay",
  "Cabernet Franc",
  "Carmenere",
  "Montepulciano d'Abruzzo",
  "Barbera",
  "Barbaresco",
  "Pinotage",
  "Mourvedre/Monastrell",
  "Petit Verdot",
  "Dolcetto",
  "Primitivo",
  "Tannat",
  "Touriga Nacional",
  "Aglianico",
  "Nero d'Avola",
  "Mencia",
  "Cinsault",
  "Corvina",
  "Dornfelder",
  "Blaufränkisch",
  "Zweigelt",
  "Bobal",
  "Negroamaro",
  "Xinomavro",
  "Sagrantino",
  "Tinta de Toro",
  "Alicante Bouschet",
  "Carignan/Carignano",
  "Durif/Petite Sirah",
  "Lagrein",
  "Tinta Roriz",
  "Baga",
  "Bonarda/Charbono",
  "Graciano",
  "Trousseau",
  "Valpolicella Blend",
  "Priorat Blend",
  "Châteauneuf-du-Pape Blend",
  "Bordeaux Blend",
  "Super Tuscan Blend",
  "Rhone Blend",
  "Rioja Blend",
  "Ribera del Duero",
  "Barolo",
  "Brunello di Montalcino",
  "Amarone della Valpolicella",
  "Chianti",
  "Pomerol and Saint-Émilion",
  "Côte-Rôtie",
  "Hermitage",
  "Cornas",
  "Saint-Joseph",
  "Côte de Nuits",
  "Côte de Beaune",
  "Pauillac",
  "Margaux",
  "Saint-Julien",
  "Haut-Médoc",
  "Saint-Estèphe",
  "Pessac-Léognan",
  "Graves",
  "Sauternes",
  "Bandol",
  "Tavel",
  "Côtes du Rhône",
  "Gigondas",
  "Vacqueyras",
  "Lirac",
  "Taurasi",
  "Vino Nobile di Montepulciano",
  "Rosso di Montalcino",
  "Morellino di Scansano",
  "Montefalco Rosso",
  "Carmignano",
  "Bolgheri",
  "Amarone della Valpolicella",
  "Ripasso della Valpolicella",
  "Recioto della Valpolicella",
  "Bardolino",
  "Soave",
  "Valpolicella",
  "Chianti Classico",
  "Chianti Rufina",
  "Chianti Colli Senesi",
  "Chianti Colli Fiorentini",
  "Chianti Montespertoli",
  "Chianti Montalbano",
  "Chianti Colli Aretini",
  "Chianti Colli Pisane",
];

export const whiteVarietals = [
  "Chardonnay",
  "Sauvignon Blanc",
  "Riesling",
  "Pinot Grigio/Pinot Gris",
  "Gewürztraminer",
  "Moscato/Muscat",
  "Semillon",
  "Viognier",
  "Chenin Blanc",
  "Verdejo",
  "Albariño",
  "Torrontés",
  "Garganega",
  "Vermentino",
  "Trebbiano/Ugni Blanc",
  "Grüner Veltliner",
  "Marsanne",
  "Roussanne",
  "Melon de Bourgogne",
  "Grenache Blanc",
  "Picpoul",
  "Furmint",
  "Sylvaner",
  "Müller-Thurgau",
  "Pinot Blanc",
  "Arneis",
  "Falanghina",
  "Verdicchio",
  "Fiano",
  "Greco",
  "Cortese",
  "Godello",
  "Assyrtiko",
  "Chasselas",
  "Scheurebe",
  "Vidal Blanc",
  "Champagne Blend",
  "Burgundy White (Chardonnay)",
  "Chablis (Chardonnay)",
  "Pouilly-Fuissé (Chardonnay)",
  "Meursault (Chardonnay)",
  "Montrachet (Chardonnay)",
  "Sancerre (Sauvignon Blanc)",
  "Pouilly-Fumé (Sauvignon Blanc)",
  "Vouvray (Chenin Blanc)",
  "Savennières (Chenin Blanc)",
  "Alsace Riesling",
  "Alsace Gewürztraminer",
  "Alsace Pinot Gris",
  "Muscadet (Melon de Bourgogne)",
  "Soave (Garganega)",
  "Verdicchio dei Castelli di Jesi (Verdicchio)",
  "Vermentino di Gallura (Vermentino)",
  "Fiano di Avellino (Fiano)",
  "Greco di Tufo (Greco)",
  "Gavi (Cortese)",
  "Orvieto (Trebbiano, Grechetto)",
  "Muscadet Sèvre-et-Maine (Melon de Bourgogne)",
  "Tokaji (Furmint, Hárslevelű)",
  "Sauternes (Sémillon, Sauvignon Blanc, Muscadelle)",
  "Barsac (Sémillon, Sauvignon Blanc, Muscadelle)",
  "Monbazillac (Sémillon, Sauvignon Blanc, Muscadelle)",
  "Jurançon (Gros Manseng, Petit Manseng)",
  "Pacherenc du Vic-Bilh (Petit Courbu, Petit Manseng)",
  "Vouvray Moelleux (Chenin Blanc)",
  "Quarts de Chaume (Chenin Blanc)",
  "Bonnezeaux (Chenin Blanc)",
  "Coteaux du Layon (Chenin Blanc)",
];
