export const redVarietals = [
  "Cabernet Sauvignon",
  "Merlot",
  "Pinot Noir",
  "Syrah/Shiraz",
  "Zinfandel",
  "Malbec",
  "Sangiovese",
  "Tempranillo",
  "Grenache/Garnacha",
  "Nebbiolo",
  "Barbera",
  "Carmenere",
  "Tempranillo",
  "Petit Verdot",
  "Tannat",
  "Aglianico",
  "Montepulciano d'Abruzzo",
  "Pinotage",
  "Mourvedre/Monastrell",
  "Nero d'Avola",
  "Gamay",
  "Cabernet Franc",
  "Primitivo",
  "Dolcetto",
  "Touriga Nacional",
  "Mencia",
  "Cinsault",
  "Corvina",
  "Zweigelt",
  "Blaufränkisch",
  "Bobal",
  "Xinomavro",
  "Sagrantino",
  "Tinta de Toro",
  "Alicante Bouschet",
  "Durif/Petite Sirah",
  "Lagrein",
  "Tinta Roriz",
  "Baga",
  "Bonarda/Charbono",
  "Graciano",
  "Valpolicella Blend",
  "Barolo",
  "Brunello di Montalcino",
  "Chianti",
  "Bordeaux Blend",
  "Super Tuscan Blend",
  "Rhone Blend",
  "Rioja Blend",
  "Priorat Blend",
  "Pomerol",
  "Saint-Émilion",
  "Côte-Rôtie",
  "Hermitage",
  "Cornas",
  "Saint-Joseph",
  "Côte de Nuits",
  "Côte de Beaune",
  "Pauillac",
  "Margaux",
  "Saint-Julien",
  "Haut-Médoc",
  "Saint-Estèphe",
  "Pessac-Léognan",
  "Graves",
  "Sauternes",
  "Bandol",
  "Tavel",
  "Côtes du Rhône",
  "Gigondas",
];

export const whiteVarietals = [
  "Chardonnay",
  "Sauvignon Blanc",
  "Riesling",
  "Pinot Grigio",
  "Gewürztraminer",
  "Viognier",
  "Albariño",
  "Chenin Blanc",
  "Vermentino",
  "Semillon",
  "Muscadet",
  "Torrontés",
  "Fiano",
  "Verdelho",
  "Grüner Veltliner",
  "Marsanne",
  "Picpoul",
  "Assyrtiko",
  "Greco di Tufo",
  "Trebbiano",
  "Sylvaner",
  "Cortese",
  "Arinto",
  "Falanghina",
  "Vouvray",
  "Colombard",
  "Ugni Blanc",
  "Falernia",
  "Pecorino",
  "Xarel-lo",
  "Bacchus",
  "Melon de Bourgogne",
  "Müller-Thurgau",
  "Aligoté",
  "Ribolla Gialla",
  "Godello",
  "Verdicchio",
  "Ortega",
  "Welschriesling",
  "Jacquère",
  "Marsanne",
  "Rkatsiteli",
  "Coda di Volpe",
  "Scheurebe",
  "Graševina",
  "Zibibbo",
  "Malvasia",
  "Viura",
  "Chasselas",
  "Auxerrois",
];
export const sparklingVarietals = [
  "Prosecco",
  "Champagne",
  "Cava",
  "Asti Spumante",
  "Franciacorta",
  "Crémant",
  "Sekt",
  "Lambrusco",
  "Moscato d'Asti",
  "Cap Classique",
  "Pétillant Naturel",
  "Brachetto d'Acqui",
  "Espumante",
  "Cremant de Loire",
  "Cremant de Bourgogne",
  "Sercial Madeira",
  "Pignoletto",
  "Penedès Cava",
  "Riesling Sekt",
  "Blanquette de Limoux",
];
